local AttackVM = require("src.systems.attack_vm")

describe("AttackVM variables and math", function()
    it("SET stores a value and $ resolves it", function()
        local vm = AttackVM.new()
        vm:execute("SET", { "Speed", 200 })
        assert_eq(vm:resolve("$Speed"), 200)
    end)

    it("resolve passes plain values through", function()
        local vm = AttackVM.new()
        assert_eq(vm:resolve(42), 42)
        assert_eq(vm:resolve("hello"), "hello")
    end)

    it("unset variables resolve to 0", function()
        local vm = AttackVM.new()
        assert_eq(vm:resolve("$Nothing"), 0)
    end)

    it("SET copies another variable through $", function()
        local vm = AttackVM.new()
        vm:execute("SET", { "A", 7 })
        vm:execute("SET", { "B", "$A" })
        assert_eq(vm:resolve("$B"), 7)
    end)

    it("ADD SUB MUL DIV MOD compute and store", function()
        local vm = AttackVM.new()
        vm:execute("ADD", { "R", 2, 3 })
        assert_eq(vm:resolve("$R"), 5)
        vm:execute("SUB", { "R", "$R", 1 })
        assert_eq(vm:resolve("$R"), 4)
        vm:execute("MUL", { "R", "$R", 3 })
        assert_eq(vm:resolve("$R"), 12)
        vm:execute("DIV", { "R", "$R", 5 })
        assert_near(vm:resolve("$R"), 2.4)
        vm:execute("MOD", { "R", 7, 3 })
        assert_eq(vm:resolve("$R"), 1)
    end)

    it("FLOOR truncates down", function()
        local vm = AttackVM.new()
        vm:execute("FLOOR", { "F", 3.9 })
        assert_eq(vm:resolve("$F"), 3)
    end)

    it("DEG and RAD convert angles", function()
        local vm = AttackVM.new()
        vm:execute("RAD", { "R", 180 })
        assert_near(vm:resolve("$R"), math.pi)
        vm:execute("DEG", { "D", math.pi })
        assert_near(vm:resolve("$D"), 180)
    end)

    it("SIN and COS take degrees", function()
        local vm = AttackVM.new()
        vm:execute("SIN", { "S", 90 })
        assert_near(vm:resolve("$S"), 1)
        vm:execute("COS", { "C", 0 })
        assert_near(vm:resolve("$C"), 1)
    end)

    it("ANGLE stores degrees from point 1 to point 2", function()
        local vm = AttackVM.new()
        vm:execute("ANGLE", { "A", 0, 0, 10, 0 })
        assert_near(vm:resolve("$A"), 0)
        vm:execute("ANGLE", { "A", 0, 0, 0, 10 })
        assert_near(vm:resolve("$A"), 90)
        vm:execute("ANGLE", { "A", 5, 5, 0, 5 })
        assert_near(math.abs(vm:resolve("$A")), 180)
    end)

    it("RND stays within 0 to n-1", function()
        local vm = AttackVM.new()
        for _ = 1, 100 do
            vm:execute("RND", { "V", 4 })
            local v = vm:resolve("$V")
            assert_true(v >= 0 and v <= 3 and v == math.floor(v), "RND range")
        end
    end)

    it("isOp recognizes opcodes and rejects commands", function()
        local vm = AttackVM.new()
        assert_true(vm:isOp("ADD"))
        assert_true(vm:isOp("JMPABS"))
        assert_true(not vm:isOp("BoneV"))
        assert_true(not vm:isOp("EndAttack"))
    end)

    it("execute raises a clear error on unknown opcode", function()
        local vm = AttackVM.new()
        local ok, err = pcall(function() vm:execute("NOPE", {}) end)
        assert_true(not ok, "unknown opcode must error")
        assert_true(tostring(err):find("unknown opcode"), "error names the problem")
    end)
end)

describe("AttackVM jumps", function()
    it("JMPABS returns an absolute jump with label or number target", function()
        local vm = AttackVM.new()
        local jump = vm:execute("JMPABS", { "StartLoop" })
        assert_eq(jump.type, "abs")
        assert_eq(jump.target, "StartLoop")
        jump = vm:execute("JMPABS", { 6 })
        assert_eq(jump.target, 6)
    end)

    it("JMPABS resolves $var targets", function()
        local vm = AttackVM.new()
        vm:execute("SET", { "Where", 14 })
        local jump = vm:execute("JMPABS", { "$Where" })
        assert_eq(jump.target, 14)
    end)

    it("JMPREL returns a relative offset, $var allowed", function()
        local vm = AttackVM.new()
        local jump = vm:execute("JMPREL", { 4 })
        assert_eq(jump.type, "rel")
        assert_eq(jump.offset, 4)
        vm:execute("SET", { "Jump", -3 })
        jump = vm:execute("JMPREL", { "$Jump" })
        assert_eq(jump.offset, -3)
    end)

    it("JMPZ jumps only when the value is zero", function()
        local vm = AttackVM.new()
        assert_true(vm:execute("JMPZ", { "End", 0 }) ~= nil)
        assert_true(vm:execute("JMPZ", { "End", 5 }) == nil)
    end)

    it("JMPNZ jumps only when the value is not zero", function()
        local vm = AttackVM.new()
        assert_true(vm:execute("JMPNZ", { "End", 5 }) ~= nil)
        assert_true(vm:execute("JMPNZ", { "End", 0 }) == nil)
    end)

    it("JMPE and JMPNE compare two values", function()
        local vm = AttackVM.new()
        assert_true(vm:execute("JMPE", { 10, 3, 3 }) ~= nil)
        assert_true(vm:execute("JMPE", { 10, 3, 4 }) == nil)
        assert_true(vm:execute("JMPNE", { 10, 3, 4 }) ~= nil)
        assert_true(vm:execute("JMPNE", { 10, 3, 3 }) == nil)
    end)

    it("JMPL JMPNL JMPG JMPNG ordering comparisons", function()
        local vm = AttackVM.new()
        assert_true(vm:execute("JMPL", { 10, 1, 2 }) ~= nil)
        assert_true(vm:execute("JMPL", { 10, 2, 2 }) == nil)
        assert_true(vm:execute("JMPNL", { 10, 2, 2 }) ~= nil)
        assert_true(vm:execute("JMPNL", { 10, 1, 2 }) == nil)
        assert_true(vm:execute("JMPNL", { 10, 3, 2 }) ~= nil)
        assert_true(vm:execute("JMPG", { 10, 3, 2 }) ~= nil)
        assert_true(vm:execute("JMPG", { 10, 2, 2 }) == nil)
        assert_true(vm:execute("JMPNG", { 10, 2, 2 }) ~= nil)
        assert_true(vm:execute("JMPNG", { 10, 3, 2 }) == nil)
        assert_true(vm:execute("JMPNG", { 10, 1, 2 }) ~= nil)
    end)
end)
