local AttackVM = require("src.systems.attack_vm")

describe("AttackVM variables and math", function()
    it("SET stores a value and $ resolves it", function()
        local vm = AttackVM.new()
        vm:execute("SET", { "Speed", 200 })
        assert_eq(vm:resolve("$Speed"), 200)
    end)

    it("resolve passes plain values through", function()
        local vm = AttackVM.new()
        assert_eq(vm:resolve(42), 42)
        assert_eq(vm:resolve("hello"), "hello")
    end)

    it("unset variables resolve to 0", function()
        local vm = AttackVM.new()
        assert_eq(vm:resolve("$Nothing"), 0)
    end)

    it("SET copies another variable through $", function()
        local vm = AttackVM.new()
        vm:execute("SET", { "A", 7 })
        vm:execute("SET", { "B", "$A" })
        assert_eq(vm:resolve("$B"), 7)
    end)

    it("ADD SUB MUL DIV MOD compute and store", function()
        local vm = AttackVM.new()
        vm:execute("ADD", { "R", 2, 3 })
        assert_eq(vm:resolve("$R"), 5)
        vm:execute("SUB", { "R", "$R", 1 })
        assert_eq(vm:resolve("$R"), 4)
        vm:execute("MUL", { "R", "$R", 3 })
        assert_eq(vm:resolve("$R"), 12)
        vm:execute("DIV", { "R", "$R", 5 })
        assert_near(vm:resolve("$R"), 2.4)
        vm:execute("MOD", { "R", 7, 3 })
        assert_eq(vm:resolve("$R"), 1)
    end)

    it("FLOOR truncates down", function()
        local vm = AttackVM.new()
        vm:execute("FLOOR", { "F", 3.9 })
        assert_eq(vm:resolve("$F"), 3)
    end)

    it("DEG and RAD convert angles", function()
        local vm = AttackVM.new()
        vm:execute("RAD", { "R", 180 })
        assert_near(vm:resolve("$R"), math.pi)
        vm:execute("DEG", { "D", math.pi })
        assert_near(vm:resolve("$D"), 180)
    end)

    it("SIN and COS take degrees", function()
        local vm = AttackVM.new()
        vm:execute("SIN", { "S", 90 })
        assert_near(vm:resolve("$S"), 1)
        vm:execute("COS", { "C", 0 })
        assert_near(vm:resolve("$C"), 1)
    end)

    it("ANGLE stores degrees from point 1 to point 2", function()
        local vm = AttackVM.new()
        vm:execute("ANGLE", { "A", 0, 0, 10, 0 })
        assert_near(vm:resolve("$A"), 0)
        vm:execute("ANGLE", { "A", 0, 0, 0, 10 })
        assert_near(vm:resolve("$A"), 90)
        vm:execute("ANGLE", { "A", 5, 5, 0, 5 })
        assert_near(math.abs(vm:resolve("$A")), 180)
    end)

    it("RND stays within 0 to n-1", function()
        local vm = AttackVM.new()
        for _ = 1, 100 do
            vm:execute("RND", { "V", 4 })
            local v = vm:resolve("$V")
            assert_true(v >= 0 and v <= 3 and v == math.floor(v), "RND range")
        end
    end)

    it("isOp recognizes opcodes and rejects commands", function()
        local vm = AttackVM.new()
        assert_true(vm:isOp("ADD"))
        assert_true(vm:isOp("JMPABS"))
        assert_true(not vm:isOp("BoneV"))
        assert_true(not vm:isOp("EndAttack"))
    end)
end)
